package MyPackEnterprise;
// Generated 09-jun-2019 17:53:31 by Hibernate Tools 5.2.3.Final

/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

	private int id;
	private String country;
	private String name;

	public Client() {
	}

	public Client(int id, String country, String name) {
		this.id = id;
		this.country = country;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
